import type { Dict } from "./dictionary";

export const zh: Dict = {
  nav: {
    home: "首页",
    about: "关于我们",
    leadership: "领导成员",
    membership: "成为会员",
  },
  footer: {
    aboutTitle: "巴基斯坦-中国友好协会",
    aboutText:
      "一个位于巴基斯坦拉合尔的、非政府、非营利性质的志愿组织，致力于加强巴基斯坦人民与中国人民之间的友谊纽带。",
    estNote:
      "正式成立于2026年8月20日，旨在促进巴基斯坦与中国之间的人文交流与友谊。",
    quickLinks: "快速链接",
    membership: "会员",
    membershipInfo: "如何成为会员",
    contact: "位置",
    location: "巴基斯坦 拉合尔",
    emailLabel: "电子邮件",
    rights: "版权所有。",
    established: "成立于2026年8月20日",
    langNote: "English / 中文",
  },
  home: {
    heroEyebrow: "巴基斯坦 - 中国",
    heroTitle: "巴基斯坦-中国友好协会",
    heroSubtitle: "非营利 · 非政府 · 志愿组织 - 巴基斯坦 拉合尔",
    heroIntro:
      "巴基斯坦-中国友好协会（PCFA）拉合尔于2026年8月20日正式成立，旨在通过社会、文化、教育、经济和娱乐等方面的互动，拉近巴基斯坦人民与中国人民之间的距离。",
    heroCta: "成为会员",
    heroCtaSecondary: "了解更多",
    heroImageCaption: "中国国家主席习近平与巴基斯坦总理穆罕默德·夏巴兹·谢里夫",
    xiCaption: "中华人民共和国主席习近平",
    shehbazCaption: "巴基斯坦总理穆罕默德·夏巴兹·谢里夫",
    diplomaticEyebrow: "致敬领导力与友谊",
    eventEyebrow: "PCFA 拉合尔",
    eventTitle: "PCFA 拉合尔成立会议",
    eventText:
      "这张照片记录了巴基斯坦-中国友好协会（拉合尔）的成立会议，标志着协会通过社会、文化、教育、经济和娱乐等方面的互动，拉近巴基斯坦人民与中国人民距离的工作正式开始。",
    eventText2:
      "会议汇聚了致力于促进两国人民之间人文交流、相互理解、友谊与合作的人士。",
    consulEyebrow: "支持拉合尔的友好交流",
    consulTitle: "孙岩",
    consulRole: "中华人民共和国驻拉合尔总领事",
    consulText:
      "孙岩总领事推动旁遮普省人文交流与合作的工作，与 PCFA 拉合尔的宗旨相契合。他对相互理解、文化交流和持久中巴友谊的鼓励，为协会开展工作提供了重要启发。",
    introTitle: "关于PCFA拉合尔",
    introText:
      "一个致力于加强巴基斯坦与中国之间友谊纽带的非营利、非政府志愿组织。",
    peopleTitle: "人文交流项目",
    peopleText:
      "PCFA将不时组织各种活动和项目，促进两国人民之间的人文交流、相互理解、友谊与合作。",
    peopleFocus: {
      title: "人文交流",
      text: "通过定期的社会、文化和社区互动，拉近巴基斯坦人民与中国人民之间的距离。",
    },
    peopleMission: {
      title: "相互理解",
      text: "通过庆祝两国重要的国家和文化节日，加深友谊与合作。",
    },
    peopleScope: {
      title: "广泛合作",
      text: "促进巴基斯坦人民与中国人民之间学术、文化、经济和娱乐方面的交流。",
    },
    pillarsTitle: "我们的重点领域",
    pillars: [
      { title: "社会与文化", text: "庆祝两国重要的国家和文化节日。" },
      { title: "教育", text: "研讨会、会议、展览、语言课程与互访交流。" },
      { title: "经济", text: "促进企业、智库与民间社会组织之间的合作。" },
      { title: "娱乐交流", text: "让两个社区更加贴近的友谊项目。" },
    ],
    objectivesTitle: "我们的目标",
    objectives: [
      "庆祝两国重要的国家和文化节日。",
      "加强巴基斯坦与中国之间的人文关系。",
      "组织研讨会、会议、展览、文化节、语言课程和互访交流。",
      "促进教育机构、智库、企业和民间社会组织之间的合作。",
      "在PCFA内设立中国院校巴基斯坦校友分会。",
    ],
    activitiesTitle: "我们的项目",
    activities: [
      { title: "研讨会与会议", text: "促进巴基斯坦与中国机构之间对话、研究与交流的学术聚会。" },
      { title: "展览与文化节", text: "庆祝两国重要国家和文化节日的活动。" },
      { title: "语言课程", text: "增进两个社区之间沟通与理解的语言学习机会。" },
      { title: "互访交流", text: "建立持久个人、学术和机构联系的访问与代表团交流。" },
    ],
    liaisonTitle: "与中国驻拉合尔总领事馆的联络",
    liaisonText:
      "PCFA与中国驻拉合尔总领事馆保持联络与协调，共同庆祝两国重要的国家和文化节日，并组织联合活动。",
    ctaTitle: "成为会员",
    ctaText: "加入PCFA拉合尔，共同巩固巴基斯坦与中国之间持久的友谊。",
    ctaTitleDark: "与我们共筑友谊",
    ctaTextDark: "凡认同巴中两国人民友谊与合作宗旨的人士均可申请加入。",
    ctaButton: "申请入会",
    visionTitle: "我们的愿景",
    visionText:
      "促进和加强巴基斯坦人民与中国人民之间学术、文化、经济和娱乐关系与合作，并与中国驻拉合尔总领事馆保持联络。",
    alumniTitle: "校友分会",
    alumniText:
      "PCFA正在为中国院校深造的巴基斯坦人设立校友分会，创建一个由亲身体验过中国的个人组成的持久网络，为两国之间的友谊做出贡献。",
    membershipTitle: "会员",
    membershipText:
      "认同本协会巴中友谊宗旨的人士均可申请成为PCFA拉合尔会员。本协会同时为对巴中友好事业做出贡献的人士授予荣誉会员称号。",
  },
  about: {
    title: "关于PCFA",
    eyebrow: "我们是谁",
    introTitle: "关于本协会",
    introText:
      "巴基斯坦-中国友好协会（PCFA）拉合尔于2026年8月20日正式成立，旨在通过社会、文化、教育、经济和娱乐等方面的互动，拉近巴基斯坦人民与中国人民之间的距离。",
    natureTitle: "我们的性质",
    natureText:
      "PCFA是一个位于巴基斯坦拉合尔的非营利、非政府志愿组织。它是一个民间组织，其力量来自认同巴中友谊宗旨的市民、专业人士、学者和商界领袖的自愿参与。",
    purposeTitle: "我们的宗旨",
    purposeText:
      "本协会致力于促进两国人民之间的人文交流、相互理解、友谊与合作，并与中国驻拉合尔总领事馆保持联络与协调。",
    visionTitle: "我们的愿景",
    visionText:
      "促进和加强巴基斯坦人民与中国人民之间学术、文化、经济和娱乐关系与合作，并与中国驻拉合尔总领事馆保持联络。",
    objectivesTitle: "我们的目标",
    objectives: [
      "庆祝两国重要的国家和文化节日。",
      "加强巴基斯坦与中国之间的人文关系。",
      "组织研讨会、会议、展览、文化节、语言课程和互访交流。",
      "促进教育机构、智库、企业和民间社会组织之间的合作。",
      "在PCFA内设立中国院校巴基斯坦校友分会。",
    ],
    activitiesTitle: "我们的活动",
    activitiesText:
      "PCFA将不时组织各种活动和项目，促进两国人民之间的人文交流、相互理解、友谊与合作。",
    activities: [
      { title: "研讨会与会议", text: "促进巴基斯坦与中国机构之间对话、研究与交流的学术聚会。" },
      { title: "展览与文化节", text: "庆祝两国重要国家和文化节日的活动。" },
      { title: "语言课程", text: "增进两个社区之间沟通与理解的语言学习机会。" },
      { title: "互访交流", text: "建立持久个人、学术和机构联系的访问与代表团交流。" },
    ],
    collaborationTitle: "合作与伙伴关系",
    collaborationText:
      "PCFA促进两国教育机构、智库、企业和民间社会组织之间的合作，建立学术关系、文化关系、经济合作与娱乐合作。",
    alumniTitle: "校友分会",
    alumniText:
      "PCFA正在为中国院校深造的巴基斯坦人设立校友分会，创建一个由亲身体验过中国的个人组成的持久网络，为两国之间的友谊做出贡献。",
    membershipTitle: "会员",
    membershipText:
      "认同本协会巴中友谊宗旨的人士均可申请成为PCFA拉合尔会员。本协会同时为对巴中友好事业做出贡献的人士授予荣誉会员称号。",
    ctaTitle: "成为会员",
    ctaText: "加入PCFA拉合尔，共同巩固巴基斯坦与中国之间持久的友谊。",
    ctaButton: "申请入会",
    associationLabel: "PCFA 拉合尔",
    countriesLabel: "巴基斯坦与中国",
    directionLabel: "我们的方向",
    focusLabel: "我们的重点",
    programmesLabel: "活动项目",
    togetherLabel: "携手合作",
    networkLabel: "持久的联系网络",
    statsEstablished: "成立",
    statsYear: "2026",
    statsFounders: "创始成员",
    statsProgrammes: "项目",
  },
  leadership: {
    title: "执行委员会",
    eyebrow: "PCFA 拉合尔",
    subtitle: "了解按职务资历排序、共同指导 PCFA 拉合尔的委员会成员。",
    president: "PCFA 主席",
    secretaryGeneral: "PCFA 秘书长",
    jointSecretary: "PCFA 副秘书长",
    memberEC: "PCFA 执行委员会成员",
    member: "PCFA 成员",
    seniorVP: "PCFA 高级副会长",
    dean: "中央旁遮普大学 院长",
    ownerDirector: "IMC医院（Defence区）所有人兼董事",
    director: "Sufi工业集团 董事",
    formerDG: "旁遮普省政府 前税务总局局长",
    gcuLahore: "拉合尔GC大学",
  },
  founders: {
    eyebrow: "巴基斯坦-中国友好协会，拉合尔",
    title: "创始成员",
    intro: "这些成员的投入与领导力共同促成了 PCFA 拉合尔的成立。",
    photoUnavailable: "暂无照片",
  },
  membership: {
    title: "成为会员",
    eyebrow: "加入PCFA拉合尔",
    subtitle: "申请成为巴基斯坦-中国友好协会（拉合尔）会员。",
    successTitle: "申请已提交",
    successText:
      "感谢您有兴趣加入PCFA拉合尔。我们已收到您的申请，并向您发送了确认邮件。我们的团队将审核您的申请并尽快与您联系。",
    backHome: "返回首页",
    form: {
      fullName: "姓名",
      email: "电子邮箱",
      phone: "电话号码",
      country: "国家",
      city: "城市",
      organization: "单位 / 机构",
      designation: "职务",
      education: "学历 / 背景",
      reason: "您为什么想加入PCFA？",
      submit: "提交申请",
      submitting: "提交中...",
      required: "必填",
    },
  },
  admin: {
    loginTitle: "管理员登录",
    loginSubtitle: "PCFA拉合尔 - 管理后台",
    email: "电子邮箱",
    password: "密码",
    signIn: "登录",
    signingIn: "登录中...",
    invalid: "邮箱或密码无效。",
    signOut: "退出登录",
    applications: "申请管理",
    members: "会员管理",
    newsletter: "新闻通讯",
    pending: "待审核",
    approved: "已批准",
    rejected: "已拒绝",
    approve: "批准",
    reject: "拒绝",
    noApplications: "暂无申请。",
    noMembers: "暂无已批准会员。",
    newsletterSubject: "主题",
    newsletterMessage: "内容",
    sendNewsletter: "发送给所有会员",
    sending: "发送中...",
    newsletterSuccess: "新闻通讯发送成功。",
    newsletterError: "新闻通讯发送失败。",
    applicantDetails: "申请人详情",
    status: "状态",
    date: "日期",
    actions: "操作",
    close: "关闭",
    addMemberTitle: "添加会员",
    memberAdded: "会员添加成功。",
    memberAddError: "会员添加失败。",
    applicationApproved: "申请已成功批准。",
    applicationRejected: "申请已成功拒绝。",
  },
  common: {
    language: "Translate to English / 翻译成英文",
    loading: "加载中...",
  },
};
