"use client";

import { useCallback, useEffect, useState } from "react";
import type { EventItem } from "@/lib/types";

type Form = { title: string; title_zh: string; description: string; description_zh: string; event_date: string; location: string; cover_image_url: string; status: "draft" | "published" };
const empty: Form = { title: "", title_zh: "", description: "", description_zh: "", event_date: "", location: "", cover_image_url: "", status: "draft" };
const toForm = (event: EventItem): Form => ({ title: event.title, title_zh: event.title_zh || "", description: event.description || "", description_zh: event.description_zh || "", event_date: event.event_date || "", location: event.location || "", cover_image_url: event.cover_image_url || "", status: event.status });

export default function EventsTab() {
  const [events, setEvents] = useState<EventItem[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<string | null>(null); const [file, setFile] = useState<File | null>(null); const [notice, setNotice] = useState("");
  const load = useCallback(() => fetch("/api/admin/events").then((res) => res.json()).then((data) => setEvents(data.events || [])), []);
  useEffect(() => { load(); }, [load]);
  const change = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function upload() { if (!file) return form.cover_image_url; const data = new FormData(); data.set("file", file); const res = await fetch("/api/admin/uploads", { method: "POST", body: data }); const result = await res.json(); if (!res.ok) throw new Error(result.error || "Upload failed"); return result.url as string; }
  async function save(event: React.FormEvent) { event.preventDefault(); setNotice(""); try { const cover_image_url = await upload(); const res = await fetch("/api/admin/events", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, cover_image_url, ...(editing ? { id: editing } : {}) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not save event"); setForm(empty); setEditing(null); setFile(null); setNotice("Event saved."); load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save event"); } }
  async function remove(id: string) { if (!window.confirm("Delete this event?")) return; await fetch("/api/admin/events", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); load(); }
  return <div className="space-y-6"><form onSubmit={save} className="rounded-xl border border-slate-200 bg-brand-light p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-brand-blue">{editing ? "Edit event" : "New event"}</h2>{editing && <button type="button" className="text-sm text-brand-red" onClick={() => { setEditing(null); setForm(empty); }}>Cancel</button>}</div><div className="grid gap-4 sm:grid-cols-2"><Input label="Title (English)" required value={form.title} onChange={(v) => change("title", v)} /><Input label="Title (Chinese)" value={form.title_zh} onChange={(v) => change("title_zh", v)} /><Input label="Date" type="date" value={form.event_date} onChange={(v) => change("event_date", v)} /><Input label="Location" value={form.location} onChange={(v) => change("location", v)} /><Input label="Description (English)" textarea value={form.description} onChange={(v) => change("description", v)} /><Input label="Description (Chinese)" textarea value={form.description_zh} onChange={(v) => change("description_zh", v)} /><label className="text-sm font-medium text-brand-slate">Cover image<input className="mt-1 block w-full text-sm" type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><label className="text-sm font-medium text-brand-slate">Status<select className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2" value={form.status} onChange={(e) => change("status", e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label></div>{notice && <p className="mt-4 text-sm text-brand-red">{notice}</p>}<button className="mt-5 rounded-lg bg-brand-blue px-5 py-2.5 text-sm font-bold text-white">Save event</button></form><div className="grid gap-4">{events.map((event) => <article key={event.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold text-brand-blue">{event.title}</h3><p className="mt-1 text-sm text-brand-slate">{event.event_date || "No date"} · {event.status}</p></div><div className="flex gap-4 text-sm font-semibold"><button className="text-brand-blue" onClick={() => { setEditing(event.id); setForm(toForm(event)); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button><button className="text-brand-red" onClick={() => remove(event.id)}>Delete</button></div></article>)}</div></div>;
}
function Input({ label, value, onChange, required, textarea, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; textarea?: boolean; type?: string }) { const className = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"; return <label className="text-sm font-medium text-brand-slate">{label}{textarea ? <textarea className={className} rows={3} value={value} onChange={(e) => onChange(e.target.value)} /> : <input required={required} type={type} className={className} value={value} onChange={(e) => onChange(e.target.value)} />}</label>; }
