"use client";

import { useCallback, useEffect, useState } from "react";
import type { GalleryPost } from "@/lib/types";

type Form = { title: string; title_zh: string; description: string; description_zh: string; event_date: string; status: "draft" | "published" };
const empty: Form = { title: "", title_zh: "", description: "", description_zh: "", event_date: "", status: "draft" };
const toForm = (post: GalleryPost): Form => ({ title: post.title, title_zh: post.title_zh || "", description: post.description || "", description_zh: post.description_zh || "", event_date: post.event_date || "", status: post.status });

export default function GalleryTab() {
  const [posts, setPosts] = useState<GalleryPost[]>([]); const [form, setForm] = useState<Form>(empty); const [urls, setUrls] = useState<string[]>([]); const [editing, setEditing] = useState<string | null>(null); const [notice, setNotice] = useState("");
  const load = useCallback(() => fetch("/api/admin/gallery").then((res) => res.json()).then((data) => setPosts(data.posts || [])), []);
  useEffect(() => { load(); }, [load]);
  const change = (key: keyof Form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function addFiles(files: FileList | null) { if (!files?.length) return; setNotice("Uploading images..."); try { const uploaded = await Promise.all([...files].map(async (file) => { const data = new FormData(); data.set("file", file); const res = await fetch("/api/admin/uploads", { method: "POST", body: data }); const result = await res.json(); if (!res.ok) throw new Error(result.error || "Upload failed"); return result.url as string; })); setUrls((current) => [...current, ...uploaded]); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Upload failed"); } }
  async function save(event: React.FormEvent) { event.preventDefault(); setNotice(""); const res = await fetch("/api/admin/gallery", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, image_urls: urls, ...(editing ? { id: editing } : {}) }) }); const data = await res.json(); if (!res.ok) { setNotice(data.error || "Could not save gallery post"); return; } setForm(empty); setUrls([]); setEditing(null); setNotice("Gallery post saved."); load(); }
  async function remove(id: string) { if (!window.confirm("Delete this gallery post?")) return; await fetch("/api/admin/gallery", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); load(); }
  return <div className="space-y-6"><form onSubmit={save} className="rounded-xl border border-slate-200 bg-brand-light p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-brand-blue">{editing ? "Edit gallery post" : "New gallery post"}</h2>{editing && <button type="button" className="text-sm text-brand-red" onClick={() => { setEditing(null); setForm(empty); setUrls([]); }}>Cancel</button>}</div><div className="grid gap-4 sm:grid-cols-2"><Input label="Title (English)" required value={form.title} onChange={(v) => change("title", v)} /><Input label="Title (Chinese)" value={form.title_zh} onChange={(v) => change("title_zh", v)} /><Input label="Date" type="date" value={form.event_date} onChange={(v) => change("event_date", v)} /><label className="text-sm font-medium text-brand-slate">Status<select className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2" value={form.status} onChange={(e) => change("status", e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><Input label="Description (English)" textarea value={form.description} onChange={(v) => change("description", v)} /><Input label="Description (Chinese)" textarea value={form.description_zh} onChange={(v) => change("description_zh", v)} /></div><label className="mt-4 block text-sm font-medium text-brand-slate">Images<input className="mt-1 block w-full text-sm" type="file" accept="image/*" multiple onChange={(e) => addFiles(e.target.files)} /></label>{urls.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{urls.map((url) => <div key={url} className="flex max-w-48 items-center gap-2 rounded bg-white px-2 py-1 text-xs"><span className="truncate">Image</span><button type="button" className="text-brand-red" onClick={() => setUrls((current) => current.filter((item) => item !== url))}>Remove</button></div>)}</div>}{notice && <p className="mt-4 text-sm text-brand-red">{notice}</p>}<button className="mt-5 rounded-lg bg-brand-blue px-5 py-2.5 text-sm font-bold text-white">Save gallery post</button></form><div className="grid gap-4">{posts.map((post) => <article key={post.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold text-brand-blue">{post.title}</h3><p className="mt-1 text-sm text-brand-slate">{post.images.length} image{post.images.length === 1 ? "" : "s"} · {post.status}</p></div><div className="flex gap-4 text-sm font-semibold"><button className="text-brand-blue" onClick={() => { setEditing(post.id); setForm(toForm(post)); setUrls(post.images.map((image) => image.image_url)); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button><button className="text-brand-red" onClick={() => remove(post.id)}>Delete</button></div></article>)}</div></div>;
}
function Input({ label, value, onChange, required, textarea, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; textarea?: boolean; type?: string }) { const className = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"; return <label className="text-sm font-medium text-brand-slate">{label}{textarea ? <textarea className={className} rows={3} value={value} onChange={(e) => onChange(e.target.value)} /> : <input required={required} type={type} className={className} value={value} onChange={(e) => onChange(e.target.value)} />}</label>; }
